set background=light
set autochdir
highlight CursorLine gui=underline guifg=NONE guibg=NONE

" GUI related options
" Remove toolbar and menubar
set guioptions-=T
set guioptions-=m

" IMEの状態でカーソル色を変更する
if has('multi_byte_ime')
  highlight Cursor guifg=NONE guibg=Green
  highlight CursorIM guifg=NONE guibg=Purple
endif
