if filereadable($VIMRUNTIME . "/defaults.vim")
	source $VIMRUNTIME/defaults.vim
endif

set encoding=utf8
scriptencoding utf8

if has("win32")
	if has("gui_running")
		set runtimepath+=$XDG_CONFIG_HOME\vim
	endif
endif


set viminfo+='1000,n$XDG_CACHE_HOME/vim/viminfo

set nu
set display+=lastline
set autochdir
set cursorline
set visualbell
set splitright
set splitbelow
set noswapfile
set showcmd
set completeopt+=longest
set wildmode=list:longest
set list
set listchars=tab:⋮\ ,trail:⎵,extends:⟩,precedes:⟨,nbsp:□
set hlsearch " highlight search word
set infercase " ignore case when completing words
autocmd FileType * setlocal formatoptions-=r formatoptions-=o
syntax on

" Default Indent Config
set shiftwidth=4
set tabstop=4
set noexpandtab
set smartindent

set background=dark


let mapleader=","

" 通常のエディタにあるショートカット
map <Space> <c-f>
map <s-Space> <c-b>
nnoremap <S-CR> O<esc>
nnoremap <CR> o<esc>

" Clipboard
noremap <C-y> "+P
inoremap <C-y> <C-r>+
noremap <C-A-y> "*P

" go to the middle of a line by gm
noremap gm :call cursor(0, virtcol('$')/2)<CR>

" カーソル下の単語を置換する
nnoremap g* :%s/\<<C-r><C-w>\>/
vnoremap g* :s/\<<C-r><C-w>\>/
" 検索ハイライトをクリア
nnoremap <silent> <Esc><Esc> :<C-u>nohlsearch<CR>

" duplicate current line
nnoremap <A-c> yyp

source $XDG_CONFIG_HOME/vim/rc/dvorak_op.vim
source $XDG_CONFIG_HOME/vim/rc/vundle.vim
source $XDG_CONFIG_HOME/vim/rc/myftdetect.vim

