source $VIMRUNTIME/defaults.vim

if has("win32")
		if has("gui_running")
				set runtimepath+=$XDG_CONFIG_HOME\vim
		endif
endif


set viminfo+='1000,n$XDG_CACHE_HOME/vim/viminfo

set nu
set display+=lastline
set autochdir
set autoindent
set background=dark
set cursorline
set visualbell
set splitright
if !has("win32") && !has("win32unix")
  set list
  set listchars=tab:⋮\ ,trail:⎵,extends:⟩,precedes:⟨,nbsp:□
endif
set hlsearch " highlight search word
set infercase " ignore case when completing words
syntax on
highlight CursorLine term=underline ctermfg=NONE ctermbg=NONE


map <Space> <c-f>
map <s-Space> <c-b>
map <F2> :w<CR>:make<CR>
" go to the middle of a line by gm
noremap gm :call cursor(0, virtcol('$')/2)<CR>

:command! Brol browse old
:command! Erc tabnew $MYVIMRC
:command! Egrc tabnew $MYGVIMRC

source $XDG_CONFIG_HOME/vim/rc/dvorak_op.vim
source $XDG_CONFIG_HOME/vim/rc/vundle.vim

