# THIS IS EXPERIMENTAL
# the config file schema may change at any time

style:
  tag:
    color: magenta # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 5 # column width relative to the terminal window
    min_width: 3 # minimum column width as number of characters
  comment:
    color: white
    width_percentage: 30
    min_width: 15
  snippet:
    width_percentage: 65
    color: blue

# finder:
#   command: fzf # equivalent to the --finder option
  # overrides: --tac # equivalent to the --fzf-overrides option
  # overrides_var: --tac # equivalent to the --fzf-overrides-var option

# cheats:
#   paths:
#     - /path/to/some/dir # on unix-like os
#     - F:\\path\\to\\dir # on Windows
# path: /path/to/some/dir # (DEPRECATED) equivalent to the --path option

# search:
# tags: git,!checkout # equivalent to the --tag-rules option

# shell:
  # Shell used for shell out. Possible values: bash, zsh, dash, ...
  # For Windows, use `cmd.exe` instead.
  # command: bash
  
  # finder_command: bash # similar, but for fzf's internals

