git:
  commit:
    autoWrapCommitMessage: false
  autoForwardBranches: none
  pagers:
    - pager: delta --paging=never

os:
  editPreset: "nvim-remote"

gui:
  tabWidth: 2
  spinner:
    frames: [🌑, 🌒, 🌓, 🌔, 🌕, 🌖, 🌗, 🌘]
    rate: 300
  nerdFontsVersion: "3"

keybinding:
  universal:
    executeShellCommand: "$"
