# If not running interactively, don't do anything
case $- in
	*i*) ;;
	*) return;;
esac

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_CACHE_HOME="${HOME}/.cache"
CONF_DIR=${XDG_CONFIG_HOME}/bash


# History Configuration
# ----------------------------
# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth
# append to the history file, don't overwrite it
shopt -s histappend
export HISTFILESIZE=20000
export HISTIGNORE='sudo *:*;sudo *:*; sudo *:l:history:history *'
export PROMPT_COMMAND="${PROMPT_COMMAND}history -a;"

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar


# Color Configuration
# --------------------------
# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

source "${CONF_DIR}/ps1.sh"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	IS_COLOR_AVAILABLE=1
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
	if [ -f /usr/share/bash-completion/bash_completion ]; then
		. /usr/share/bash-completion/bash_completion
	elif [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
	fi
fi

# terminal shortcuts
stty sane
stty stop undef

# autocd: cd can be omitted when an argument is given
shopt -s autocd
shopt -s cdspell
shopt -s dirspell

export FIGNORE=__pycache__

alias graph="graph -T X"
alias cvlc="cvlc --play-and-exit -q"
alias info="info --vi-keys"

alias diff="diff --ignore-space-change --ignore-trailing-space"
alias cdiff="git diff --no-index"
alias rg="rg --smart-case"
export DELTA_DEFAULT_OPTION="--dark --theme DarkNeon --file-color cyan --hunk-style plain"
alias delta="delta $DELTA_DEFAULT_OPTION"

type -t bat > /dev/null && export MANPAGER="sh -c 'col -bx | bat -l man -p'"

LESS_COMMAND=$(
	type -t bat > /dev/null && echo bat \
	|| (type -t lv > /dev/null && echo lv) \
	|| echo less
)
alias less=$LESS_COMMAND
OPEN_COMMAND=$(
	type -t exo-open > /dev/null  && echo exo-open \
	|| (type -t xdg-open > /dev/null && echo xdg-open) \
	|| (type -t start > /dev/null && echo start) \
	|| echo open
)
alias open=$OPEN_COMMAND
LS_COMMAND=$(
	type -t exa > /dev/null && echo exa \
	|| ([ "$IS_COLOR_AVAILABLE" = 1 ] && echo ls --color=auto -p) \
	|| echo ls
)
alias ls=$LS_COMMAND

# time style for `ls -l` command output
TIME_STYLE=long-iso

PATH="${CONF_DIR}/../bin:$PATH"


# Load additional configuration files
# --------------------------------
# loadLazily trigger_command other_triggers source_file [arguments ...]
mybashrc::lazyLoad::loadLazily() {
	local TRIGGER_COMMAND=$1
	for trig in ${2//,/ }; do
		unalias $trig
	done
	source "$3"
	shift 3
	$TRIGGER_COMMAND "$@"
}

if [ $(uname -s) = Darwin ]; then
	MAC_RC="${CONF_DIR}/macrc/*.sh"
fi
for x in ${CONF_DIR}/rc/*.sh $MAC_RC; do
	if [[ "$x" != *".lazy"* ]]; then
		# T=$(gdate +'1%-S%N')
		source $x
		# echo -e $(( ($(gdate +'1%-S%N') - $T) / 100000 )) "\t" $x
	else
		# Extract trigger command: formats=TRIGGER.lazy.sh or foo.lazy=TRIGGER,TRIG2.sh
		filename=$(basename $x)
		lazy=${filename##*.lazy}
		lazy=${lazy%%.*}
		if [ "${lazy:0:1}" != "=" ]; then
			trigger_commands=${filename%%.lazy*}
		else
			trigger_commands=${lazy:1}
		fi

		for trig in ${trigger_commands//,/ }; do
			alias $trig="mybashrc::lazyLoad::loadLazily $trig $trigger_commands \"$x\""
		done
	fi
done

