shared:
  timeout: &timeout
    timeout_millis: 200


modmap:
  - name: Dvorak
    remap:
      # 1st row
      MINUS: LEFTBRACE  # -: @
      # EQUAL: EQUAL  # ^: ^
      # YEN: YEN  # ¥: ¥

      # 2st row
      q: APOSTROPHE # JP colon
      w: COMMA
      e: DOT
      r: p
      t: y
      y: f
      u: g
      i: c
      o: r
      p: l
      LEFTBRACE: SLASH  # @: /
      # RIGHTBRACE: RIGHTBRACE  # [: [

      # 3rd row
      # a: a
      s: o
      d: e
      f: u
      g: i
      KEY_H: d
      KEY_J: h
      k: t
      l: n
      SEMICOLON: s  # ;: s
      APOSTROPHE: MINUS  # :: -
      # BACKSLASH: BACKSLASH  # ]: ]

      # 4th row
      z: SEMICOLON  # z: ;
      x: q
      c: j
      v: k
      b: x
      n: b
      # m: m
      COMMA: w
      DOT: v
      SLASH: z
      # RO: RO  # \: \

  - name: Modifiers
    remap:
      CAPSLOCK: BACKSPACE
      SPACE:
        alone: SPACE
        held: LEFTSHIFT
        <<: *timeout
      MUHENKAN:
        alone: MUHENKAN
        held: F23
        <<: *timeout
      HENKAN:
        alone: HENKAN
        held: RIGHTCTRL
        <<: *timeout
      KEY_KATAKANAHIRAGANA: RIGHTALT

virtual_modifiers:
  - F23
  - F24

keymap:
  - name: Logical Shift
    remap:
      F23-1: F1
      F23-2: F2
      F23-3: F3
      F23-4: F4
      F23-5: F5
      F23-6: F6
      F23-7: F7
      F23-8: F8
      F23-9: F9
      F23-0: F10
      F23-LEFTBRACE: F11  # @
      F23-EQUAL: F12  # ^

      F23-APOSTROPHE: ESC
      F23-COMMA: DELETE
      F23-DOT: HOME
      F23-p: END
      F23-c: ENTER
      
      # 3rd row
      F23-BACKSPACE: BACK
      F23-a: C-a
      F23-o: C-o
      F23-e: PAGEUP
      F23-u: PAGEDOWN
      
      F23-d: LEFT
      F23-h: DOWN
      F23-t: UP
      F23-n: RIGHT
      
      # 4th row
      F23-SEMICOLON: C-z
      F23-q: C-x
      F23-j: C-c
      F23-k: C-v

  - remap:
      SHIFT-0: SHIFT-YEN

