shared:
  timeout: &timeout
    timeout_millis: 200


modmap:
  - name: Dvorak
    remap:
      # 1st row
      MINUS: LEFTBRACE  # -: @
      # EQUAL: EQUAL  # ^: ^
      # YEN: YEN  # ¥: ¥

      # 2st row
      q: APOSTROPHE # JP colon
      w: COMMA
      e: DOT
      r: p
      t: y
      y: f
      u: g
      i: c
      o: r
      p: l
      LEFTBRACE: SLASH  # @: /
      # RIGHTBRACE: RIGHTBRACE  # [: [

      # 3rd row
      # a: a
      s: o
      d: e
      f: u
      g: i
      KEY_H: d
      KEY_J: h
      k: t
      l: n
      SEMICOLON: s  # ;: s
      APOSTROPHE: MINUS  # :: -
      # BACKSLASH: BACKSLASH  # ]: ]

      # 4th row
      z: SEMICOLON  # z: ;
      x: q
      c: j
      v: k
      b: x
      n: b
      # m: m
      COMMA: w
      DOT: v
      SLASH: z
      # RO: RO  # \: \

  - name: Modifiers
    remap:
      CAPSLOCK: BACKSPACE
      SPACE:
        alone: SPACE
        held: LEFTSHIFT
        <<: *timeout
      MUHENKAN:
        alone: MUHENKAN
        held: F23
        <<: *timeout

  - device:
      not: &dumang
        - "www.BeyondQ.com DuMang KeyBoard DK6"
    remap:
      HENKAN:
        alone: HENKAN
        held: RIGHTCTRL
        <<: *timeout
      KEY_KATAKANAHIRAGANA: RIGHTALT

  - name: Dumang
    device:
      only: *dumang
    remap:
      ENTER:
        alone: ENTER
        held: RIGHTCTRL
        <<: *timeout
      HENKAN:
        alone: HENKAN
        held: F24
        <<: *timeout

virtual_modifiers:
  - F23
  - F24

keymap:
  - name: Logical Shift
    remap:
      F23-1: F1
      F23-2: F2
      F23-3: F3
      F23-4: F4
      F23-5: F5
      F23-6: F6
      F23-7: F7
      F23-8: F8
      F23-9: F9
      F23-0: F10
      F23-LEFTBRACE: F11  # @
      F23-EQUAL: F12  # ^

      F23-APOSTROPHE: ESC
      F23-COMMA: DELETE
      F23-DOT: HOME
      F23-p: END
      F23-c: ENTER
      
      # 3rd row
      F23-BACKSPACE: BACK
      F23-a: C-a
      F23-o: C-s
      F23-e: PAGEUP
      F23-u: PAGEDOWN
      
      F23-d: LEFT
      F23-h: DOWN
      F23-t: UP
      F23-n: RIGHT
      
      # 4th row
      F23-SEMICOLON: C-z
      F23-q: C-x
      F23-j: C-c
      F23-k: C-v

  - name: Symbol Layer
    remap:
      F24-p: EQUAL  # ^
      F24-g: RO  # \
      F24-c: RIGHTBRACE  # [
      F24-r: BACKSLASH  # ]
      F24-l: SHIFT-YEN  # |

      F24-a: "1"
      F24-o: "2"
      F24-e: "3"
      F24-u: "4"
      F24-i: "5"
      F24-d: "6"
      F24-h: "7"
      F24-t: "8"
      F24-n: "9"
      F24-s: "0"
      F23-F24-a: F1
      F23-F24-o: F2
      F23-F24-e: F3
      F23-F24-u: F4
      F23-F24-i: F5
      F23-F24-d: F6
      F23-F24-h: F7
      F23-F24-t: F8
      F23-F24-n: F9
      F23-F24-s: F10
      F23-F24-c: F11
      F23-F24-r: F12

      F24-q: LEFTBRACE  # @
      F24-b: SHIFT-RO  # _

  - remap:
      SHIFT-0: SHIFT-YEN
      SHIFT-F24-s: SHIFT-YEN

